### PR TITLE
flac/avcc: bound Vec::with_capacity in parse_vorbis_comment and Avcc

### LINKED ISSUE #154: Unbounded `Vec::with_capacity` in `parse_vorbis_comment` and `Avcc`
Two `Vec::with_capacity` call sites use a `u32` read straight from the input as the capacity argument. Other equivalent sites in the crate already cap with `min(...)` - it looks like these two were missed.

## The two sites

`src/moov/trak/mdia/minf/stbl/stsd/flac.rs:189`:

```rust
let number_of_fields = u32::from_le_bytes(<[u8; 4]>::decode(buf)?) as usize;
let mut comments = Vec::with_capacity(number_of_fields);
```

`Vec<String>` is 24 bytes per slot, so a `u32::MAX` here asks for ~103 GiB.

`src/moov/trak/mdia/minf/stbl/stsd/h264/avcc.rs:97`:

```rust
Vec::with_capacity(num_of_sequence_parameter_set_exts);
```

Same shape, smaller per-element type.

## What the rest of the crate does

The capped equivalents:

```
src/sidx.rs:48              Vec::with_capacity(std::cmp::min(reference_count as usize, 128))
src/mfra/tfra.rs:111        Vec::with_capacity(std::cmp::min(128, number_of_entry as usize))
src/moof/traf/trun.rs:61    Vec::with_capacity(sample_count.min(4096) as _)
```

The pattern is "trust the count for upfront reservation only up to N; the actual Vec grows past N via `push`". Decode still fails cleanly on truncation because the per-element reads return `Error::OutOfBounds`.

## Repro

Found this fuzzing kei's HEIC XMP probe (which calls `Any::decode_maybe` in a loop). 110 bytes:

```
00000000: 0000 0008 001d 0022 0000 0000 6466 4c61
00000010: 0000 00f6 6a00 0010 0daa 6b9d bbff ff00
00000020: 0000 0c0c 0c0c 1b00 0400 001d 0000 0000
00000030: 666c 3634 0032 0000 0000 0000 0001 0000
00000040: 0800 0000 4fe0 0000 0000 0000 0000 0a00
00000050: 2200 0000 6466 4c61 0000 00f6 6a00 0010
00000060: 0daa 6b9d bbff ff00 0000 0c0c 0000
```

Run through any `Any::decode_maybe` loop. ASan reports `out-of-memory (malloc(21023566224))`. Backtrace:

```
parse_vorbis_comment                  src/.../flac.rs:189
<Dfla as Atom>::decode_body           src/atom_ext.rs:26
<Any as DecodeAtom>::decode_atom      src/any.rs:85
Any::decode_maybe                     src/any.rs:50
```

Three other independently-mutated 61-128 byte inputs hit the same site. Tested against `main` at `d1e9e923` (also reproduces on 0.10.1).

## Fix

Same `min(...)` pattern as `sidx.rs` / `tfra.rs` / `trun.rs`. Happy to send a PR; let me know if you'd prefer a specific cap value or a small shared helper since the pattern repeats.

### PR DESCRIPTION
**Pull request by rhoopr**
Closes #154.

`parse_vorbis_comment` (`src/moov/trak/mdia/minf/stbl/stsd/flac.rs`) gets:

- A pre-flight rejecting `number_of_fields` counts that can't fit in the remaining buffer. Each field carries a u32 length prefix, so anything past `buf.remaining() / 4` is structurally impossible. Returns `Error::OutOfBounds`. Same defensive idiom as `header.rs:114-117` and `trun.rs:50-60` - refuse impossible claims before allocating.
- `Vec::with_capacity` capped at 4096, matching `trun.rs:61`.

~~`Avcc` (`src/moov/trak/mdia/minf/stbl/stsd/h264/avcc.rs:97`) gets the same `min(4096)` cap. The source is a `u8` so it's a no-op in practice; included for crate-wide consistency.~~

Regression test pins `Err(Error::OutOfBounds)` via `matches!`, so it fails if the pre-flight ever regresses.

Three adjacent sites have the same shape and lack guards: `saiz.rs:54` (u32 count, 1 byte/entry, the most exposed), `saiz.rs:118` (u32, 4-8 bytes), `hvcc.rs:75` (u16, 2 bytes). Tracked as #156, scoped separately to keep this PR focused on #154.

Second commit hoists the existing inline `// See RFC 9639...` comments onto `parse_stream_info` and `parse_vorbis_comment` as proper `///` docstrings (no new prose, just relocation). Addresses CodeRabbit's docstring-coverage warning.

## Test plan

- [x] `cargo test --all-features` (207 pass, including new regression)
- [x] `cargo clippy --all-targets --all-features -- -D warnings` clean
- [x] Original 110-byte fuzz input from #154 now decodes one atom and returns `Err(OverDecode(dfLa))` (which wraps the inner `Err(OutOfBounds)` from the new pre-flight). No OOM. Verified by running the input through `Any::decode_maybe` in a loop.

### CODE REVIEW

**Comment by rhoopr** [comment]
@bradh when I opened this, GH was being really flaky - not sure if that's why CI failed but I don't think it's the PR - can you check/rerun?

File: src/moov/trak/mdia/minf/stbl/stsd/h264/avcc.rs [hunk 1]
```diff
@@ -94,7 +94,7 @@ impl Atom for Avcc {
             let bit_depth_chroma_minus8 = u8::decode(buf)? & 0x7;
             let num_of_sequence_parameter_set_exts = u8::decode(buf)? as usize;
             let mut sequence_parameter_sets_ext =
-                Vec::with_capacity(num_of_sequence_parameter_set_exts);
+                Vec::with_capacity(num_of_sequence_parameter_set_exts.min(4096));
```
Comment (bradh) [inline src/moov/trak/mdia/minf/stbl/stsd/h264/avcc.rs]: Since this can never exceed 255, I think I'd prefer to just skip the `min()` part. The magic 4096 was based on reading a u32 or similar.

**Review by bradh — COMMENTED** [review]
The vorbis parts LGTM.

File: src/moov/trak/mdia/minf/stbl/stsd/h264/avcc.rs (hunk 1 above)
Comment (rhoopr) [reply src/moov/trak/mdia/minf/stbl/stsd/h264/avcc.rs]: Reverted AVCC change. It was a consistency no-op anyway.

**Review by bradh — APPROVED** [review]
